package com.example.cerbo.entity.enums;

public enum TypeDocument {
    DESCRIPTIF_PROJET,
    CONSIDERATION_ETHIQUE,
    FICHE_INFORMATION_FRANCAIS,
    FICHE_INFORMATION_ARABE,
    FICHE_CONSENTEMENT_FRANCAIS,
    FICHE_CONSENTEMENT_ARABE,
    ATTESTATION_ENGAGEMENT,
    ATTESTATION_CNDP,
    CV_INVESTIGATEUR,
    SUPPORT_FORMATION,
    PIECE_JOINTE_ARTICLE,
    PROGRAMME_EVENEMENT,
    AUTRE
}